version: "3"
services:
  django:
    build: ./django
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./django:/code
      - static:/code/static_root
      - media:/code/media
